### ISSUE TITLE
Raise KeyError when `provide` doesn't find given name

### ISSUE THREAD

**Issue by matino** [jaapverloop/knot#1]
Current behaviour of the `Container.provide` method is to return `None` when a dependency is not found. Wouldn't it be better to raise an exception instead (KeyError for example)? I think I'd want to fail as fast as possible when I have given the incorrect `name` and stop the application instead of having a delayed "None type objects has no attribute ..." error.

**Comment by jaapverloop** [comment]
At the moment it's possible to pass a default return value in case a name is not registered. AFAIK this wouldn't be possible with the change you're suggesting. I guess the current funcionality of passing in a default return value is not that important IMHO. I'm willing to sacrifice the current behaviour in favor of this change. So, feel free to send a PR and I will merge. Thanks in advance!

**Comment by matino** [comment]
Here you go - https://github.com/jaapverloop/knot/pull/2
